version: '3'
services:

  redis:
    image: redis:latest
  
  rabbitmq:
    image: rabbitmq:latest

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'celery -A tasks worker --loglevel=INFO'
    depends_on:
      - rabbitmq
      - redis